### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by ra-pha** [KhalidWar/anonaddy#25]
Hi,

iOS 14.5.1.
iPhone 11

Just started using the app and find it quite useful but found that I'm confronted quickly with an error message:

**_Too many requests - you're sending too many requests or have reached your limit for new alises._**

, even when I don't make an action in  the app. So essentially I suspect a bug which either makes that the error message is triggered.

I use anonaddy Pro and therefore I shouldn't hit any limits in terms of new aliases (as the error message suggests).

Any idea how to get around this maybe?

**Comment by KhalidWar** [comment]
Hi Rapha,

Limitation is coming from AnonAddy's API, which AddyManager utilizes to interact with AnonAddy server, and has nothing to do with account subscription. **It's an app issue not account or subscription related**. 

As a user, you can't get around this as it's out of your reach. Perhaps removing app, when not in use, from recent apps (background) might help.

It looks like AddyManager is exceeding the 120 requests per minute. I'm on it.

Thanks for reporting this issue.

**Comment by KhalidWar** [comment]
I've managed to implement a way to stop API calls when app is in background (#30) which should help with this error.

Commit link: https://github.com/KhalidWar/anonaddy/pull/30/commits/36dfe745993b16b2743a1ffb2d49b4349d71fa7a

Closing this issue as it's solved. Will reopen if it comes back.
