### ISSUE TITLE
Self-hosted support

### ISSUE THREAD

**Issue by lbr88** [KhalidWar/anonaddy#28]
Hi, your app looks great. 
This is a feature request for support for the selfhosted version. It would be great if you were able to set your own host/url when adding the token.

**Comment by KhalidWar** [comment]
Thanks. Added to Upcoming Features' list.

**Comment by vonProteus** [comment]
Hi
Any timeline on this feature? @KhalidWar

**Comment by KhalidWar** [comment]
Hi @vonProteus,
Unfortunately, I can't put a time on when this will be available. 
I've been working on improving the backend and how data is handled throughout the app, slow and time consuming process.

Reopening this issue as it's a priority now.

**Comment by KhalidWar** [comment]
Added self host support as BETA, meaning there MIGHT be some unexpected bugs.

App store update will be available next week.
