### ISSUE TITLE
Incorrect API Endpoints

### ISSUE THREAD

**Issue by httpjamesm** [KhalidWar/anonaddy#54]
In the latest AddyManager update, the app is unable to fetch data from the API, maybe due to a configuration or environment variable issue. 

It is trying to connect to https:/api/... instead of AnonAddy. 

Screenshot is below. 

![image](https://user-images.githubusercontent.com/51917118/157260134-cef1187f-3090-4aa5-9a03-6059e3b10b77.jpeg)

**Comment by KhalidWar** [comment]
This error occurs when there's no instance URL has been specified or app fails to fetch stored URL (which is most likely the case here). 

Possible solution:
- Log out, force close app, then log back in. This solves majority of issues.

Let me know if this issue persists.

**Comment by httpjamesm** [comment]
Thanks, that worked. Maybe have the app automatically log out if this event occurs?

**Comment by KhalidWar** [comment]
That's awesome. 

I added that this morning. App now automatically logs out if it can't log in with access token and instance url.

https://github.com/KhalidWar/anonaddy/commit/f48b00240b1c5baed45da78eab68d172baa75b80
