### ISSUE TITLE
list of deleted alias twice

### ISSUE THREAD

**Issue by tioannidis** [KhalidWar/anonaddy#55]
If I open the list of deleted alias everything is okay, but two seconds later the entry’s are twice.

I use an Ipad 9.gen with 15.3.1 (19D52) and addyManager 2.7.13(35)

![926431A1-A057-4795-B877-9E926756CB0C](https://user-images.githubusercontent.com/1592909/158260267-de82df11-5e95-4ee7-bfad-4396947abb90.jpeg)

**Comment by tioannidis** [comment]
@KhalidWar thx for your quick feedback.

I can confirm that your app works perfect on my Mac
![Unbenannt1](https://user-images.githubusercontent.com/1592909/158633514-a7e27102-8ad5-4535-a011-29099ad08532.png)

**Comment by KhalidWar** [comment]
Fixed.

Fix will be available in the next update.

https://github.com/KhalidWar/anonaddy/commit/b0051fe54467da96bdbd4bd93ae0df0ce0d4bf26
