### ISSUE TITLE
duplicate display of active alias

### ISSUE THREAD

**Issue by straef** [KhalidWar/anonaddy#56]
#55 related but where they are seeing deleted aliases twice, i am seeing all active and inactive alias twice. i have no deleted alias, so do not see those twice.
![Screenshot_20220412-151013~2](https://user-images.githubusercontent.com/20950411/163047783-fc9d16c1-df65-40e5-83e2-8dd49539f4b5.png)

i am on android with latest playstore release as of 2022-apr-12.

**Comment by straef** [comment]
issue persists after logging out and re-entering api key

**Comment by KhalidWar** [comment]
Thanks for reporting this, @straef .

I'm aware of this issue and working on a fix. 

It's caused by pagination (fetching extra aliases) and is not related to your account, api key, or cache. It happens when you have less than 20 aliases (available or deleted).

**Comment by KhalidWar** [comment]
Fixed.

Fix will be available in the next update.

https://github.com/KhalidWar/anonaddy/commit/b0051fe54467da96bdbd4bd93ae0df0ce0d4bf26
