### ISSUE TITLE
Still displaying duplicates of aliases

### ISSUE THREAD

**Issue by W3LLD0NE** [KhalidWar/anonaddy#60]
Related to #56 I think.

Steps:
1. Open app on 'Available aliases' page;
2. Go to 'Deleted aliases' page, wait a bit and then go back to 'Available aliases';
3. Now scroll to the bottom and you should find xN (where N is a total count of registered aliases - 1, for example for 17 it would be 16) duplicates of each alias displayed. In contrast to #56, where you have A,B,C,D,A,B,C,D repeat order, now it is A,B,C,D,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,B,B,B,...B and so on.

Context:
-Android app v2.8.1+39 (same on iOS app v2.8.0+38)
-17 available aliases + 0 deleted aliases.

**Comment by KhalidWar** [comment]
This is a very weird one. 

It doesn't happen on my main account with lots of aliases but it does on my small test account with fewer aliases. 

@W3LLD0NE Can you create 3 more aliases (to hit total of 20 available aliases) and see if this issue occurs?

**Comment by W3LLD0NE** [comment]
@KhalidWar yes it seems not reproduceable on 20+ aliases.

**Comment by KhalidWar** [comment]
As suspected.

I'm classifying this issue as low-priority and will exist for a while. Leaving #60 open, though.

I'm reworking how available and deleted aliases are fetched, processed, and displayed. The new way will be a lot better than what I have now. Hopefully, there won't be any more duplicate issues afterwards.

Thanks for taking the time to report this issue.

**Comment by KhalidWar** [comment]
Fixed.

This change also eliminates any issues that may arise from aliases. Available and Deleted aliases now each has its own pipeline. No more mixing or filtering which would result in a smoother running app without hiccups when processing aliases.

https://github.com/KhalidWar/anonaddy/commit/5f7765f79fa84a659852cae0423b2c10d7d66bc1
