### ISSUE TITLE
[UI] [iOS] aliases not visible in Dark mode

### ISSUE THREAD

**Issue by akotas** [KhalidWar/anonaddy#7]
device iphone xs
ios 14.3

Issue: when changing UI to Dark Mode aliases font do not alter colour 
![addymanager dark mode alias font](https://user-images.githubusercontent.com/24389048/105481666-a572f380-5ca7-11eb-9e00-3043776bbcd7.jpg)

**Comment by KhalidWar** [comment]
Fixed. 

Thanks for reporting.
