### ISSUE TITLE
Touch ID prompted twice when opening the app

### ISSUE THREAD

**Issue by ghost** [KhalidWar/anonaddy#70]
I appreciate you creating this fantastic app. On my iPhone SE (3rd Generation), I'm experiencing the issue mentioned in the title. To open the app, I must touch my finger twice.

**Comment by KhalidWar** [comment]
Hi ghost,
I'm aware of that issue, and hopefully will have it fixed in the next update. It isn't as obvious when using Face ID. 

Thanks for reporting.

**Comment by KhalidWar** [comment]
Can someone with an iphone that supports Touch ID confirm if this issue still exists?

Thanks in advance.

Note: will close this issue done in a few weeks.
