### ISSUE TITLE
Please add support for all premium domains

### ISSUE THREAD

**Issue by xanoni** [KhalidWar/anonaddy#77]
Two new domains were recently added for paid users. (I'm not mentioning the specific domains here to make the lives of the blacklist curators a tiny bit more difficult.)

These two domains are currently not supported in the app and aliases can't be created for them. I imagine it's a trivial patch to have them added. Thank you!

**Comment by KhalidWar** [comment]
Thanks for your report. It's already fixed, and next app update will include it.
