### ISSUE TITLE
Send email from this alias function broken

### ISSUE THREAD

**Issue by Killtree98** [KhalidWar/anonaddy#79]
Hello, thank you for your work on this great app! Since the recent update, I noticed the function to generate the sending address only uses the alias email information for the sender and receiver (at least on iOS).
Example:
With an alias alias1@my.addy.io and an email destination user1@domain.com, the generated address is alias1+alias1=my.addy.io@my.addy.io

Thank you for your time!

**Comment by KhalidWar** [comment]
Thanks for reporting. Fixed.
