### ISSUE TITLE
Send email from this alias not working

### ISSUE THREAD

**Issue by user733626** [KhalidWar/anonaddy#80]
On iOS with app version 2.9.1(49) the feature to "send email from this alias" stopped working. 
When I enter the recipient, the address is copied as my alias instead of recipient. 
Also with dark mode, it opens white with white text so you're unabble to read what you wrote in it.

**Comment by KhalidWar** [comment]
Thanks for reporting this. It's already fixed here: https://github.com/KhalidWar/anonaddy/issues/79

Will publish a new update soon.
