### ISSUE TITLE
App seems to be removed on Play Store?

### ISSUE THREAD

**Issue by Fuuk1** [KhalidWar/anonaddy#86]
https://play.google.com/store/apps/details?id=com.khalidwar.anonaddy&hl=en&gl=US

Hi, I really like this app. Thank you so much. I just checked for app update on Play Store and noticed the app is removed or gives a "something went wrong" error. Can you fix that?

**Comment by KhalidWar** [comment]
Google decided to hit me "policy violation" after they approved my app already. I'm working on it though. 

Running thread on this issue: https://x.com/khalidwarsa/status/1779840169719287902?s=46&t=szRX-EA2LmW-kKwelEGfIw

**Comment by KhalidWar** [comment]
App is back on the Play Store: https://play.google.com/store/apps/details?id=com.khalidwar.anonaddy

Thanks for your patience.
